# Generated by Django 5.2.11 on 2026-02-20 01:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torcida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('fundacao', models.DateField(verbose_name='Data de Fundação')),
                ('mascote', models.CharField(blank=True, max_length=100)),
                ('cores', models.CharField(max_length=100, verbose_name='Cores')),
                ('logo', models.ImageField(blank=True, upload_to='logos_torcida/')),
                ('historia', models.TextField(blank=True, verbose_name='Histórico')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='gamification.partida')),
            ],
        ),
        migrations.CreateModel(
            name='Caravana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Invasão do Maracanã', max_length=200)),
                ('saida_local', models.CharField(max_length=200, verbose_name='Local de Saída')),
                ('saida_horario', models.DateTimeField(verbose_name='Horário de Saída')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vagas_totais', models.IntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gamification.partida', verbose_name='Jogo Alvo')),
                ('passageiros', models.ManyToManyField(blank=True, related_name='caravanas_inscritas', to=settings.AUTH_USER_MODEL)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caravanas', to='organizadas.torcida')),
            ],
        ),
    ]
