# Generated by Django 5.2.11 on 2026-02-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data',
            new_name='data_evento',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='partida',
        ),
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='torcida',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='torcida_eventos', to='organizadas.torcida'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
