# Generated by Django 5.2.11 on 2026-02-22 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0002_rename_data_evento_data_evento_remove_evento_partida_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='descricao',
        ),
        migrations.AddField(
            model_name='evento',
            name='imagem_capa',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='informativo',
            field=models.TextField(blank=True, help_text='Texto detalhado sobre o evento'),
        ),
    ]
