# Generated by Django 5.2.11 on 2026-02-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0003_remove_evento_descricao_evento_imagem_capa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(default='Imprensa SAT', max_length=100)),
            ],
        ),
    ]
