# Generated by Django 5.2.11 on 2026-02-24 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0004_noticia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'verbose_name': 'Notícia', 'verbose_name_plural': 'Notícias'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='Imprensa SAT', max_length=100, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(upload_to='noticias/', verbose_name='Imagem de Capa'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
