# Generated by Django 5.2.11 on 2026-03-01 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0005_alter_noticia_options_noticia_subtitulo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=500)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='posts/')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizadas_posts', to=settings.AUTH_USER_MODEL)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizadas.torcida')),
            ],
            options={
                'ordering': ['-data_criacao'],
            },
        ),
    ]
