# Generated by Django 5.2.11 on 2026-03-02 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0007_curtida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_evento',
            new_name='data',
        ),
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='informativo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='torcida_eventos', to='organizadas.torcida'),
        ),
    ]
