# Generated by Django 5.2.11 on 2026-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0008_rename_data_evento_evento_data_evento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='torcida',
            name='cor_primaria',
            field=models.CharField(default='#CD7F32', help_text='Ex: #000000 para preto, #FF0000 para vermelho', max_length=7, verbose_name='Cor Hexadecimal Principal'),
        ),
    ]
