# Generated by Django 5.2.11 on 2026-03-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0009_torcida_cor_primaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torcida',
            name='cor_primaria',
            field=models.CharField(default='#D37129', max_length=7, verbose_name='Cor Hexadecimal'),
        ),
    ]
