# Generated by Django 5.2.11 on 2026-03-11 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0010_alter_torcida_cor_primaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torcida',
            name='cores',
        ),
        migrations.AddField(
            model_name='torcida',
            name='cor_fundo',
            field=models.CharField(default='#121212', max_length=7, verbose_name='Cor de Fundo do App'),
        ),
        migrations.AddField(
            model_name='torcida',
            name='cor_secundaria',
            field=models.CharField(default='#FFFFFF', max_length=7, verbose_name='Cor Secundária'),
        ),
        migrations.AddField(
            model_name='torcida',
            name='cor_terciaria',
            field=models.CharField(default='#000000', max_length=7, verbose_name='Cor Terciária'),
        ),
        migrations.AddField(
            model_name='torcida',
            name='imagem_fundo',
            field=models.ImageField(blank=True, null=True, upload_to='fundos_torcida/', verbose_name='Imagem de Fundo (Login/App)'),
        ),
        migrations.AddField(
            model_name='torcida',
            name='lema',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lema da Torcida'),
        ),
        migrations.AddField(
            model_name='torcida',
            name='sigla',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Sigla (Ex: TJF, MV)'),
        ),
        migrations.AlterField(
            model_name='torcida',
            name='cor_primaria',
            field=models.CharField(default='#D37129', max_length=7, verbose_name='Cor Primária'),
        ),
        migrations.AlterField(
            model_name='torcida',
            name='logo',
            field=models.ImageField(blank=True, upload_to='logos_torcida/', verbose_name='Logótipo / Escudo'),
        ),
        migrations.AlterField(
            model_name='torcida',
            name='mascote',
            field=models.CharField(blank=True, max_length=100, verbose_name='Mascote'),
        ),
        migrations.AlterField(
            model_name='torcida',
            name='nome',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome da Torcida'),
        ),
    ]
