# Generated by Django 5.2.11 on 2026-03-14 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0011_remove_torcida_cores_torcida_cor_fundo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Parceiro')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parceiros/', verbose_name='Logo')),
                ('link', models.URLField(blank=True, help_text='Link para o site ou Instagram do parceiro', null=True, verbose_name='Link do Parceiro')),
                ('torcida', models.ForeignKey(blank=True, help_text='Deixe em branco se for um parceiro global da SAT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parceiros', to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Parceiro',
                'verbose_name_plural': 'Parceiros',
            },
        ),
    ]
