# Generated by Django 5.2.11 on 2026-03-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0012_parceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Nome da Campanha/Cliente')),
                ('imagem', models.ImageField(upload_to='publicidade/', verbose_name='Imagem do Banner (Retangular)')),
                ('link', models.URLField(blank=True, help_text='Link para onde o utilizador vai ao clicar', null=True, verbose_name='Link de Destino')),
                ('data_inicio', models.DateTimeField(verbose_name='Data de Início da Campanha')),
                ('data_fim', models.DateTimeField(verbose_name='Data de Término da Campanha')),
                ('tempo_exibicao', models.PositiveIntegerField(default=5, help_text='Quantos segundos este banner aparece antes de trocar para o próximo.', verbose_name='Tempo na tela (Segundos)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativar Anúncio')),
                ('torcida', models.ForeignKey(blank=True, help_text='Deixe em branco para exibir para todas as torcidas.', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Publicidade Paga',
                'verbose_name_plural': 'Publicidades Pagas',
            },
        ),
    ]
