# Generated by Django 5.2.11 on 2026-04-05 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0014_comentario'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConquistaTorcida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Ex: Maior Bandeirão, Campeão do Carnaval', max_length=150, verbose_name='Título da Conquista')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='conquistas_torcida/', verbose_name='Foto da Conquista')),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conquistas', to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Conquista',
                'verbose_name_plural': 'Conquistas',
            },
        ),
        migrations.CreateModel(
            name='FotoGaleria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='galeria_torcida/', verbose_name='Foto')),
                ('legenda', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_galeria', to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Foto da Galeria',
                'verbose_name_plural': 'Fotos da Galeria',
            },
        ),
        migrations.CreateModel(
            name='MembroDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('cargo', models.CharField(help_text='Ex: Presidente, Diretor de Bateria, Puxador', max_length=100, verbose_name='Cargo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='diretoria_torcida/', verbose_name='Foto de Perfil')),
                ('ordem', models.IntegerField(default=0, help_text='0 aparece primeiro (Ex: Presidente)', verbose_name='Ordem de Exibição')),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diretoria', to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Membro da Diretoria',
                'verbose_name_plural': 'Membros da Diretoria',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Regra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título da Regra')),
                ('descricao', models.TextField(verbose_name='Descrição da Regra')),
                ('ordem', models.IntegerField(default=1, verbose_name='Ordem (Nº da Regra)')),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='organizadas.torcida')),
            ],
            options={
                'verbose_name': 'Regra/Estatuto',
                'verbose_name_plural': 'Regras/Estatutos',
                'ordering': ['ordem'],
            },
        ),
    ]
