# Generated by Django 5.2.11 on 2026-04-16 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0015_conquistatorcida_fotogaleria_membrodiretoria_regra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caravana',
            name='partida',
        ),
    ]
