# Generated by Django 5.2.11 on 2026-04-18 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0016_remove_caravana_partida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conquistatorcida',
            options={},
        ),
        migrations.AlterModelOptions(
            name='fotogaleria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='membrodiretoria',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regra',
            options={},
        ),
        migrations.RemoveField(
            model_name='conquistatorcida',
            name='ano',
        ),
        migrations.AddField(
            model_name='conquistatorcida',
            name='data_conquista',
            field=models.DateField(blank=True, null=True, verbose_name='Data da Conquista'),
        ),
        migrations.AddField(
            model_name='conquistatorcida',
            name='icone',
            field=models.CharField(choices=[('bi-trophy', 'Troféu'), ('bi-medal', 'Medalha'), ('bi-award', 'Prémio'), ('bi-star', 'Estrela'), ('bi-lightning', 'Raio'), ('bi-fire', 'Chama'), ('bi-bullseye', 'Alvo')], default='bi-trophy', max_length=50, verbose_name='Ícone'),
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.CharField(choices=[('jogo_oficial', 'Jogo Oficial'), ('caravana', 'Caravana'), ('evento_social', 'Evento Social'), ('reuniao', 'Reunião'), ('acao_beneficente', 'Ação Beneficente')], default='evento_social', max_length=30),
        ),
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora Fim'),
        ),
        migrations.AddField(
            model_name='evento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='max_participantes',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe em branco para ilimitado', null=True, verbose_name='Máx. Participantes'),
        ),
        migrations.AddField(
            model_name='evento',
            name='raio_checkin',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='evento',
            name='xp_recompensa',
            field=models.IntegerField(default=50),
        ),
        migrations.AddField(
            model_name='fotogaleria',
            name='titulo',
            field=models.CharField(default='Foto', max_length=100, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='ano_ingresso',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ano de Ingresso'),
        ),
        migrations.AddField(
            model_name='regra',
            name='categoria',
            field=models.CharField(blank=True, help_text='Ex: Viagens, Sede, Comportamento', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='conquistatorcida',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data',
            field=models.DateTimeField(verbose_name='Data/Hora Início'),
        ),
        migrations.AlterField(
            model_name='fotogaleria',
            name='legenda',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='membrodiretoria',
            name='cargo',
            field=models.CharField(max_length=150, verbose_name='Cargo/Descrição'),
        ),
        migrations.AlterField(
            model_name='membrodiretoria',
            name='ordem',
            field=models.IntegerField(default=0, verbose_name='Ordem de Exibição'),
        ),
        migrations.AlterField(
            model_name='regra',
            name='ordem',
            field=models.IntegerField(default=1, verbose_name='Número/Ordem'),
        ),
        migrations.CreateModel(
            name='CategoriaDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Presidência, Bateria, Comunicação', max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias_diretoria', to='organizadas.torcida')),
            ],
        ),
        migrations.AddField(
            model_name='membrodiretoria',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizadas.categoriadiretoria'),
        ),
        migrations.CreateModel(
            name='ImagemEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='eventos/galeria/')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria_imagens', to='organizadas.evento')),
            ],
        ),
    ]
