# Generated by Django 5.2.11 on 2026-04-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0017_alter_conquistatorcida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torcida',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='torcida',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
