# Generated by Django 5.2.11 on 2026-04-21 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0018_alter_torcida_nome_alter_torcida_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Deixe 0.00 se for grátis', max_digits=8, verbose_name='Valor da Entrada'),
        ),
    ]
