# Generated by Django 5.2.11 on 2026-04-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0019_evento_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='torcida',
            name='time_relacionado',
            field=models.CharField(blank=True, help_text='Nome exato do time para o filtro funcionar (Ex: Flamengo, Vasco, Corinthians)', max_length=100, null=True, verbose_name='Time do Coração (Filtro)'),
        ),
    ]
