# Generated by Django 5.2.11 on 2026-05-15 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0020_torcida_time_relacionado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InscricaoPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('evento', 'Evento'), ('caravana', 'Caravana')], max_length=10)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('metodo_pagamento', models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto Bancário'), ('cartao', 'Cartão de Crédito')], default='pix', max_length=20)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('txid', models.CharField(blank=True, max_length=35, null=True)),
                ('loc_id', models.IntegerField(blank=True, null=True)),
                ('pix_copia_e_cola', models.TextField(blank=True, null=True)),
                ('pix_qrcode', models.TextField(blank=True, null=True)),
                ('caravana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='organizadas.caravana')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='organizadas.evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes_pagamento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inscrição com Pagamento',
                'verbose_name_plural': 'Inscrições com Pagamento',
            },
        ),
    ]
