# Generated by Django 5.2.11 on 2026-06-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0021_inscricaopagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='torcida',
            name='nome_pelotao',
            field=models.CharField(blank=True, default='Pelotão', help_text='Como a torcida chama seus pelotões/comandos/sub-sedes (Ex: Comando, Sub-sede, Bonde, Distrito)', max_length=50, verbose_name='Nome do Pelotão'),
        ),
    ]
