# Generated by Django 6.0.6 on 2026-06-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0022_torcida_nome_pelotao'),
    ]

    operations = [
        migrations.AddField(
            model_name='torcida',
            name='aprovacao_automatica',
            field=models.BooleanField(default=False, help_text='Se ativado, os novos sócios entram na torcida automaticamente sem precisar de aprovação manual.', verbose_name='Aprovação Automática'),
        ),
    ]
