# Generated by Django 5.2.11 on 2026-02-26 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizadas', '0005_alter_noticia_options_noticia_subtitulo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagem', models.ImageField(upload_to='produtos/')),
                ('categoria', models.CharField(max_length=100)),
                ('destaque', models.BooleanField(default=False)),
                ('torcida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizadas.torcida')),
            ],
        ),
    ]
