# Generated by Django 5.2.11 on 2026-05-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_produto_preco_promocional_alter_produto_imagem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='loc_id',
            field=models.IntegerField(blank=True, help_text='ID da location (Payload do PIX)', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_copia_e_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='pix_qrcode',
            field=models.URLField(blank=True, help_text='URL da imagem do QR Code', null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='txid',
            field=models.CharField(blank=True, help_text='ID da transação na Efí Bank', max_length=35, null=True),
        ),
    ]
