# Generated by Django 5.2.11 on 2026-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0008_pedido_bairro_pedido_cep_pedido_cidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='pix_qrcode',
            field=models.TextField(blank=True, help_text='URL ou base64 da imagem do QR Code', null=True),
        ),
    ]
