# Generated by Django 5.2.11 on 2026-05-13 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0009_alter_pedido_pix_qrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('sede', 'Pagar na Sede')], default='pix', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='retirada_sede',
            field=models.BooleanField(default=False, verbose_name='Retirar na Sede?'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('enviado', 'Enviado'), ('aguardando_retirada', 'Aguardando Retirada'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='pendente', max_length=30),
        ),
    ]
