# Generated by Django 5.2.11 on 2026-05-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0010_pedido_metodo_pagamento_pedido_retirada_sede_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pagamento',
            field=models.CharField(choices=[('pix', 'PIX'), ('boleto', 'Boleto Bancário'), ('cartao', 'Cartão de Crédito'), ('sede', 'Pagar na Sede')], default='pix', max_length=20),
        ),
    ]
