# Generated by Django 5.2.11 on 2026-02-20 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Torcida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='torcidas/escudos/')),
                ('historia', models.TextField(blank=True)),
                ('diretoria', models.TextField(blank=True)),
                ('hino', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg_cnh', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('xp_total', models.IntegerField(default=0)),
                ('nivel_atual', models.CharField(default='Bronze', max_length=50)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('time_coracao', models.CharField(blank=True, max_length=100, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='perfis/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('torcida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.torcida')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_evento', models.DateTimeField()),
                ('local', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='accounts.torcida')),
            ],
        ),
        migrations.CreateModel(
            name='Cancao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('letra', models.TextField()),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancoes', to='accounts.torcida')),
            ],
        ),
        migrations.CreateModel(
            name='Aliada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizada', models.CharField(max_length=100)),
                ('clube', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='torcidas/aliadas/')),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliadas', to='accounts.torcida')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.evento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'evento')},
            },
        ),
    ]
