# Generated by Django 5.2.11 on 2026-02-21 13:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='nivel_atual',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='time_coracao',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='xp_total',
        ),
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='complemento',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_documento_frente',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_documento_verso',
            field=models.ImageField(blank=True, upload_to='docs/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='numero',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='perfil',
            name='orgao_expedidor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='perfil',
            name='pelotao',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rede_social',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='perfil',
            name='uf',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='perfil',
            name='verificacao_facial',
            field=models.ImageField(blank=True, upload_to='selfies/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='vulgo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cpf',
            field=models.CharField(default='', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='rg_cnh',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='RG ou CNH'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='perfil',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
