# Generated by Django 5.2.11 on 2026-02-21 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_perfil_foto_remove_perfil_nivel_atual_and_more'),
        ('organizadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizadas.torcida'),
        ),
    ]
