# Generated by Django 5.2.11 on 2026-02-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_perfil_torcida'),
        ('organizadas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancao',
            name='torcida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancoes', to='organizadas.torcida'),
        ),
        migrations.AlterField(
            model_name='aliada',
            name='torcida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliadas', to='organizadas.torcida'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='torcida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='organizadas.torcida'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='torcida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizadas.torcida'),
        ),
    ]
