# Generated by Django 5.2.11 on 2026-02-22 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_cancao_torcida_alter_aliada_torcida_and_more'),
        ('content', '0002_alter_post_torcida'),
        ('social', '0003_alter_post_torcida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Torcida',
        ),
    ]
