# Generated by Django 5.2.11 on 2026-02-22 04:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_torcida'),
        ('organizadas', '0002_rename_data_evento_data_evento_remove_evento_partida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presenca',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='organizadas.evento'),
        ),
        migrations.AlterUniqueTogether(
            name='presenca',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
