# Generated by Django 5.2.11 on 2026-02-24 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_perfil_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('subtitulo', models.CharField(blank=True, max_length=255, verbose_name='Subtítulo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem', models.ImageField(upload_to='noticias/', verbose_name='Imagem de Capa')),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(default='Imprensa SAT', max_length=100, verbose_name='Autor')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
            },
        ),
    ]
