# Generated by Django 5.2.11 on 2026-03-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_perfil_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
