# Generated by Django 5.2.11 on 2026-03-01 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_checkin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('local', models.CharField(max_length=255)),
                ('data', models.DateTimeField()),
                ('xp_recompensa', models.IntegerField(default=50)),
                ('ativo', models.BooleanField(default=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('raio_checkin', models.IntegerField(default=500, help_text='Raio em metros para permitir check-in')),
            ],
        ),
        migrations.RenameField(
            model_name='checkin',
            old_name='data_criacao',
            new_name='data_registro',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='foto',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='validado',
        ),
        migrations.AlterField(
            model_name='checkin',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.evento'),
        ),
    ]
