# Generated by Django 5.2.11 on 2026-03-02 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_evento_rename_data_criacao_checkin_data_registro_and_more'),
        ('organizadas', '0008_rename_data_evento_evento_data_evento_ativo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizadas.torcida'),
        ),
    ]
