# Generated by Django 5.2.11 on 2026-03-02 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_evento_torcida'),
        ('organizadas', '0008_rename_data_evento_evento_data_evento_ativo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkin',
            old_name='data_registro',
            new_name='data_criacao',
        ),
        migrations.AddField(
            model_name='checkin',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins_accounts', to='organizadas.evento'),
        ),
    ]
