# Generated by Django 5.2.11 on 2026-03-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_rename_data_registro_checkin_data_criacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='time_coracao',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Time do Coração'),
        ),
    ]
