# Generated by Django 5.2.11 on 2026-03-16 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_perfil_time_coracao'),
        ('organizadas', '0014_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organizadas.torcida'),
        ),
    ]
