# Generated by Django 5.2.11 on 2026-04-06 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_perfil_seguidores'),
        ('organizadas', '0015_conquistatorcida_fotogaleria_membrodiretoria_regra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Plano')),
                ('descricao', models.CharField(help_text='Ex: Ideal para quem vai a todos os jogos', max_length=200, verbose_name='Descrição Curta')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço Mensal (R$)')),
                ('destaque', models.BooleanField(default=False, help_text='Vai destacar este plano visualmente', verbose_name='Plano Destaque?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Plano Ativo?')),
                ('beneficios', models.TextField(help_text='Escreva um benefício por linha. Ex:<br>Desconto em ingressos<br>Acesso ao Hub<br>Camisa Oficial', verbose_name='Lista de Benefícios')),
                ('torcida', models.ForeignKey(blank=True, help_text='Deixe em branco se for um plano global da SAT', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos', to='organizadas.torcida')),
            ],
        ),
    ]
