# Generated by Django 5.2.11 on 2026-04-06 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_planosocio'),
        ('organizadas', '0015_conquistatorcida_fotogaleria_membrodiretoria_regra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planosocio',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='planosocio',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='planosocio',
            name='beneficios',
            field=models.TextField(verbose_name='Benefícios (um por linha)'),
        ),
        migrations.AlterField(
            model_name='planosocio',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Plano Destaque?'),
        ),
        migrations.AlterField(
            model_name='planosocio',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço Mensal'),
        ),
        migrations.AlterField(
            model_name='planosocio',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='planos_socio', to='organizadas.torcida'),
        ),
    ]
