# Generated by Django 5.2.11 on 2026-04-06 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_remove_planosocio_ativo_remove_planosocio_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planosocio',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Plano Ativo?'),
        ),
    ]
