# Generated by Django 5.2.11 on 2026-04-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_planosocio_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='doc_frente',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/frente/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='doc_selfie',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/selfie/'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='doc_verso',
            field=models.ImageField(blank=True, null=True, upload_to='documentos/verso/'),
        ),
    ]
