# Generated by Django 5.2.11 on 2026-04-18 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_perfil_doc_frente_perfil_doc_selfie_perfil_doc_verso'),
        ('organizadas', '0017_alter_conquistatorcida_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='foto_documento_frente',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='foto_documento_verso',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='verificacao_facial',
        ),
        migrations.AddField(
            model_name='aliada',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aceito', 'Aceito'), ('recusado', 'Recusado')], default='pendente', max_length=20),
        ),
        migrations.AddField(
            model_name='aliada',
            name='torcida_convidada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='organizadas.torcida'),
        ),
        migrations.AddField(
            model_name='cancao',
            name='arquivo_audio',
            field=models.FileField(blank=True, null=True, upload_to='cancoes/audio/'),
        ),
        migrations.AddField(
            model_name='cancao',
            name='descricao',
            field=models.TextField(blank=True, verbose_name='Descrição/Contexto'),
        ),
        migrations.AddField(
            model_name='cancao',
            name='url_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='URL do YouTube'),
        ),
        migrations.AlterField(
            model_name='aliada',
            name='torcida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliadas_enviadas', to='organizadas.torcida'),
        ),
        migrations.CreateModel(
            name='CampoPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_campo', models.CharField(help_text='Ex: Qual o seu tamanho de camisa?', max_length=100)),
                ('obrigatorio', models.BooleanField(default=False)),
                ('torcida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_personalizados', to='organizadas.torcida')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricoSocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acao', models.DateTimeField(auto_now_add=True)),
                ('acao', models.CharField(help_text='Ex: Aprovado, Rejeitado, Documentos Enviados', max_length=100)),
                ('observacao', models.TextField(blank=True)),
                ('moderador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_kyc', to='accounts.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=255)),
                ('campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.campopersonalizado')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas_customizadas', to='accounts.perfil')),
            ],
        ),
    ]
