# Generated by Django 5.2.11 on 2026-04-18 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_perfil_foto_documento_frente_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Noticia',
        ),
    ]
