# Generated by Django 5.2.11 on 2026-04-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_assinatura_fatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='nome_mae',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome da Mãe'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nome_pai',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome do Pai'),
        ),
    ]
