# Generated by Django 5.2.11 on 2026-04-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_perfil_nome_mae_perfil_nome_pai'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
