# Generated by Django 5.2.11 on 2026-04-23 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_perfil_telefone'),
        ('organizadas', '0019_evento_valor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='caravanas_salvas',
            field=models.ManyToManyField(blank=True, related_name='salvo_por', to='organizadas.caravana'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='eventos_salvos',
            field=models.ManyToManyField(blank=True, related_name='salvo_por', to='organizadas.evento'),
        ),
        migrations.CreateModel(
            name='PresencaCaravana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_confirmacao', models.DateTimeField(auto_now_add=True)),
                ('caravana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas_caravana', to='organizadas.caravana')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'caravana')},
            },
        ),
    ]
