# Generated by Django 5.2.11 on 2026-04-24 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_perfil_caravanas_salvas_perfil_eventos_salvos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cancao',
            name='url_youtube',
        ),
        migrations.AddField(
            model_name='cancao',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link embed do vídeo', null=True),
        ),
        migrations.AlterField(
            model_name='cancao',
            name='letra',
            field=models.TextField(blank=True, help_text='Letra completa da música', null=True),
        ),
    ]
