# Generated by Django 5.2.11 on 2026-05-13 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_fatura_loc_id_fatura_pix_copia_e_cola_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='pix_qrcode',
            field=models.TextField(blank=True, help_text='URL ou base64 da imagem do QR Code', null=True),
        ),
    ]
