# Generated by Django 5.2.11 on 2026-02-22 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0001_initial'),
        ('social', '0002_post_torcida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='torcida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_noticias', to='organizadas.torcida'),
        ),
    ]
