# Generated by Django 5.2.11 on 2026-03-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_torcida'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='conteudo',
            new_name='texto',
        ),
    ]
