# Generated by Django 5.2.11 on 2026-03-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_rename_conteudo_post_texto'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_relacionado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Time Relacionado'),
        ),
    ]
