# Generated by Django 5.2.11 on 2026-04-22 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizadas', '0019_evento_valor'),
        ('social', '0005_post_time_relacionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='caravana_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos', to='organizadas.caravana'),
        ),
        migrations.AddField(
            model_name='post',
            name='conquista_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos', to='organizadas.conquistatorcida'),
        ),
        migrations.AddField(
            model_name='post',
            name='evento_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos', to='organizadas.evento'),
        ),
        migrations.AddField(
            model_name='post',
            name='foto_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compartilhamentos', to='organizadas.fotogaleria'),
        ),
    ]
