# Generated by Django 5.2.11 on 2026-02-22 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilgamificacao',
            name='nivel_atual',
        ),
        migrations.AddField(
            model_name='perfilgamificacao',
            name='nivel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gamification.nivel'),
        ),
        migrations.AlterField(
            model_name='perfilgamificacao',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_game', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfilgamificacao',
            name='xp_total',
            field=models.IntegerField(default=0),
        ),
    ]
