# Generated by Django 5.2.11 on 2026-02-24 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_remove_perfilgamificacao_nivel_atual_and_more'),
        ('organizadas', '0003_remove_evento_descricao_evento_imagem_capa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='evento',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='organizadas.evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='checkin',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='checkins/fotos/'),
        ),
        migrations.AddField(
            model_name='checkin',
            name='nome_visitante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='checkin',
            name='validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nivel',
            name='icone',
            field=models.ImageField(blank=True, null=True, upload_to='niveis/'),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='cor_tema',
            field=models.CharField(default='#D37129', max_length=7),
        ),
        migrations.AlterField(
            model_name='nivel',
            name='xp_minimo',
            field=models.IntegerField(),
        ),
    ]
