# Generated by Django 5.2.11 on 2026-02-25 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_badge_slug_checkin_evento_checkin_foto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conquista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('icone', models.CharField(help_text='Nome do ícone do Bootstrap (ex: bi-award)', max_length=50)),
                ('xp_necessario', models.IntegerField(default=0)),
                ('cor_hex', models.CharField(default='#D37129', max_length=7)),
            ],
        ),
    ]
